### ISSUE TITLE
Change prefix in configuration files

### ISSUE THREAD

**Issue by dblezek** [Mayo-QIN/grunt#1]
Currently, in it's configuration file (`gruntfile.yml`), grunt uses `@`, `<` and `>` to signify parameter, input file, and output file respectively.  Propose a change to use `#` for parameter rather than `@`.  This change will reduce confusion with `curl` commands. 

For instance the new scheme would have:

```yml
services:
  - endPoint: echo
    commandLine: ["echo", "#Message"]
    description: print a message
    defaults:
      Message: "Hi From Grunt"
  - endPoint: sleep
    commandLine: ["sleep", "#seconds"]
    description: Sleep for a while
    defaults:
      seconds: 300
  - endPoint: copy
    commandLine: ["cp", "<input", ">output"]
    description: copy a file
```
