### ISSUE TITLE
Support Slicer CLI XML format as a service endpoint

### ISSUE THREAD

**Issue by dblezek** [Mayo-QIN/grunt#4]
Slicer has a [well defined XML format](https://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/SlicerExecutionModel) to describe command line modules.  Allow grunt to expose any Slicer CLI module as an endpoint. The YML file ought to have a new section.

```
services:
  - endPoint: copy
    commandLine: ["cp", "<input", ">output"]
    description: copy a file

# Use Slicer CLI modules.  Will populate the command line by parsing the XML output from
# ./MedianImageFilter --xml
cli:
  - endPoint: median
    executable: ./MedianImageFilter
```
